// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package simple

// Injectors from injector.go:

func CreateService(isError bool) (*SimpleService, error) {
	simpleRepository := NewSimpleRepository(isError)
	simpleService, err := NewSimpleService(simpleRepository)
	if err != nil {
		return nil, err
	}
	return simpleService, nil
}

func InitializeDatabase() *DatabaseRepository {
	databaseMongoDB := NewDatabaseMongoDB()
	databasePostgreSQL := NewDatabasePostgreSQL()
	databaseRepository := NewDatabaseRepository(databaseMongoDB, databasePostgreSQL)
	return databaseRepository
}
