openapi: 3.0.0
info:
  title: Judul API
  description: Disini deskripsi terkait API yang kita buat.
  version: 0.1.1
  termsOfService: www.google.com
  contact:
    email: maomao@gmail.com
    name: maomao
    url: maomao.com
  license:
    name: apache 2.0
    url: apache.org
servers:
  [
    {
      url: "http://{{environment}}.programmerzamannow.com/api/v1",
      description: "TodoList Restful API",
      variables:
        {
          environment:
            {
              default: "dev",
              description: "Server environment",
              enum: ["dev", "qa", "prod"],
            },
        },
    },
  ]
paths: {
  /todolist: {
    get: {
      summary: "get all todolist",
      description: "only will return active todolist",
      responses: {
        default: {
          description: "GET TODOLIST" 
        }
      }
    },
    post: {
      summary: "create a new todolist",
      description: "Create new active todolist",
      responses: {
        default: {
          description: "post TODOLIST" 
        }
      },
      requestBody: {
        content: {
          application/json: {
            schema: {
              type: "object",
              properties: {
                name: {
                  type: "string",
                  required: ["true"],
                  minLength: 1
                },
                priority: {
                  type: "string",
                  required: ["true"],
                  minimum: 1
                },
                tags: {
                  type: "array",
                  items: {
                    type: "string",
                    minLength: 1
                  }
                }
              }
            }
          }
        },
        required: true
      }
    }
  },
  /todolist/:todolistId: {
    delete: {
      summary: "delete todolist",
      description: "delete a todo",
      parameters: [
        {
          name: todolistId,
          description: "todolist id for deleting",
          in: path,
          required: true,
          schema: {
            default: "",
            type: "string",
            nullable: false
          }
        }
      ],
      responses: {
        default: {
          description: "delete TODOLIST" 
        }
      }
    },
    put: {
      responses: {
        default: {
          description: "put TODOLIST" 
        }
      }
    }
  }
}
externalDocs:
  url: "http://www.youtube.com/"
  description: "Link youtube"
