openapi: 3.0.0
info:
  title: Judul API
  description: Disini deskripsi terkait API yang kita buat.
  version: 0.1.1
  termsOfService: www.google.com
  contact:
    email: maomao@gmail.com
    name: maomao
    url: maomao.com
  license:
    name: apache 2.0
    url: apache.org
servers:
  [
    {
      url: "http://{{environment}}.programmerzamannow.com/api/v1",
      description: "TodoList Restful API",
      variables:
        {
          environment:
            {
              default: "dev",
              description: "Server environment",
              enum: ["dev", "qa", "prod"],
            },
        },
    },
  ]
paths: {}
